### ISSUE TITLE
getSupportActionBar().setTitle("MyToolbar"); not working

### ISSUE THREAD

**Issue by ghost** [henrytao-me/smooth-app-bar-layout#32]
I am trying to set title to toolbar but it is showing blank...

`````` setSupportActionBar(toolbar);
        if (null != getSupportActionBar()) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setTitle("MyToolbar");
        }```

Layout: 

```<me.henrytao.smoothappbarlayout.SmoothAppBarLayout
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">
        <android.support.design.widget.CollapsingToolbarLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_scrollFlags="scroll|enterAlways|enterAlwaysCollapsed">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="@color/primary"
                app:layout_collapseMode="pin" />

        </android.support.design.widget.CollapsingToolbarLayout>

    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>```
``````

**Comment by henrytao-me** [comment]
Hi @MrDarpan 

Of course, it won't work. You have to setTitle using `CollapsingToolbarLayout`. It's from Google Support Design. 

`This setup uses CollapsingToolbarLayout’s app:layout_collapseMode="pin" to ensure that the Toolbar itself remains pinned to the top of the screen while the view collapses. Even better, when you use CollapsingToolbarLayout and Toolbar together, the title will automatically appear larger when the layout is fully visible, then transition to its default size as it is collapsed. Note that in those cases, you should call setTitle() on the CollapsingToolbarLayout, rather than on the Toolbar itself.`

Check out this link http://android-developers.blogspot.com/2015/05/android-design-support-library.html

**Comment by ghost** [comment]
I tried setTitle() on CollapsingToolbarLayout but still title is not visible, however all other icons like toolbar menu and HomeUp arrow are visible..

**Comment by henrytao-me** [comment]
It is kind of weird. We can do teamviewer if you want. Add me on skype: henrytao.me (GMT+7)

**Comment by lovebdsobuj** [comment]
You just need to remove **`CollapsingToolbarLayout`** from you **`xml`**.

**Comment by i-rtfsc** [comment]
CollapsingToolbarLayout.setTitleEnabled(false);

**Comment by JoshuaFry** [comment]
Toolbar mToolbar = findViewById(R.id.toolbar);
 mToolbar.setTitle("YourTitle");

**Comment by eoinahernBDSwiss** [comment]
disable the collapsing toolbars title. then, set supportActionbars title. thats what got it to work for me.
