### ISSUE TITLE
snap flag not works

### ISSUE THREAD

**Issue by mikluke** [henrytao-me/smooth-app-bar-layout#45]
snap not works. for example:

   <android.support.design.widget.CollapsingToolbarLayout
        android:id="@+id/collapsing_toolbar"
        android:layout_width="match_parent"
        android:layout_height="158dp"
        android:background="@drawable/main_header_background"
        app:contentScrim="@color/transparent"
        app:titleEnabled="false"
        app:layout_scrollFlags="scroll|span|enterAlwaysCollapsed">

```
    <include layout="@layout/slideshow_main"
        android:layout_height="158dp"
        android:layout_width="match_parent"
        app:layout_collapseMode="parallax" />

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:background="@color/transparent"
        android:layout_width="match_parent"
        android:layout_height="56dp"
        app:layout_collapseMode="pin"/>

</android.support.design.widget.CollapsingToolbarLayout>
```

**Comment by henrytao-me** [comment]
Hi @mikluke,

By default, `SmoothAppBarLayout` is designed for `snap` animation. I prefer don't use original AppBarLayout `snap` property. The reason is that I designed `SmoothAppBarLayout` when SupportDesign was v22. Now, I have to review the design again with v23. However, in the mean time, you can achieve the same `snap` animation with some following examples [Smooth Default](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample%2Fsrc%2Fmain%2Fres%2Flayout%2Ffragment_smooth_default.xml), [Smooth ExitUntilCollapsed](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample%2Fsrc%2Fmain%2Fres%2Flayout%2Ffragment_smooth_exit_until_collapsed.xml) [Smooth Enter Always](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample%2Fsrc%2Fmain%2Fres%2Flayout%2Ffragment_smooth_enter_always.xml)
