### ISSUE TITLE
No scroll happening when I start scrolling from SmoothAppBarLayout itself.

### ISSUE THREAD

**Issue by R4md4c** [henrytao-me/smooth-app-bar-layout#54]
Hello,

I have a long heightened SmoothAppBarLayout that it's height is computed after getting some data from an API, and a ViewPager that contains RecyclerViews.

Here is the xml of my layout

``` xml
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.view.ViewPager
        android:id="@+id/v_view_pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

    <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
        android:id="@+id/v_app_bar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        >


        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/v_collapsing_toolbar_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:titleEnabled="false">


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <com.application.view.HomeTeasersView_
                    android:id="@+id/v_home_teasers_view"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/toolbar_background"
                    android:paddingTop="?actionBarSize" />
            </LinearLayout>

            <android.support.v7.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/v_toolbar"
                style="@style/Toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="top"
                app:layout_collapseMode="pin"
                app:layout_scrollFlags="enterAlways" />

        </android.support.design.widget.CollapsingToolbarLayout>

        <android.support.design.widget.TabLayout
            android:id="@+id/v_tab_layout"
            style="@style/TabLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="enterAlways"
            app:tabGravity="fill"
            app:tabMode="scrollable" />

    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>
</android.support.design.widget.CoordinatorLayout>
```

The problem happens when the HomeTeasersView become too long that I cannot see the ViewPager, I'm stuck with unscrollable content, although If I switched to Google AppBarLayout scrolling works normally on that part, any idea why is that happening? 

If anything is not clear, I would be more than happy to elaborate.

**Comment by henrytao-me** [comment]
Hi @R4md4c 
SmoothAppBarLayout is using different approach compared to SupportDesign. ScrollView / ListView / RecyclerView need to dispatch events and control the animation. Therefore, if HomeTeasersView is too long, it can not be scrolled. Maybe there are the way to do it. Let me investigate. In the meantime, if you have any suggestion, just let me know. 

Thanks, 
Henry

**Comment by henrytao-me** [comment]
Hi @R4md4c 
I checked my examples. I actually can scroll in `CollapsingToolbarLayout` section. Does your `HomeTeasersView` have click event?

**Comment by R4md4c** [comment]
Hi @henrytao-me 
Sorry for the late reply, the `HomeTeasersView` itself does not have click events, but it contains children that have click listeners, would that make a problem?

**Comment by henrytao-me** [comment]
Yes, it causes the problem. I guess you have to dispatch touch event somehow.

**Comment by R4md4c** [comment]
I've removed the setOnClickListener calls inside the view and the scrolling works with no problems now, I'll figure out something for dispatching the touch event.

Wouldn't it be a good idea to add general interface for these kind of views and handle that interface somehow inside the SmoothAppBarLayout the same as you are doing in PagerAdapter?

**Comment by henrytao-me** [comment]
Please reopen this issue if it still exists or have any other thoughts. IMO, it's fixed.

**Comment by pablo-oses** [comment]
Is adding a comment here how I can Re-Open this ? 
I'm having this same issue appearing after migrating from AppBarLayout to SmoothAppBarLayout.

I need to have a clickable ImageView inside a CollapsingToolbarLayout inside the SmoothAppBarLayout.
And as long as the ImageView has a ClickListener the scrolling doesn't work starting the scroll on that view.

It's critical in my case as the ImageView is as big as the entire CollapsingToolbarLayout and contains the first item image that you can tap on it to transition to the all-images dedicated screen.

I reproduced this by adding a clickable view inside the CollapsingToolbarLayout of your samples project screens GsdScrollExitUntilCollapsedActivity and SmoothScrollExitUntilCollapsedActivity to confirm the problem is in SmoothAppBarLayout.

I took a look and compared the onTouch events of the clickable view on each of those examples while starting a scroll and noticed that in the GsdScrollExitUntilCollapsedActivity case it receives the ACTION_DOWN... then a few ACTION_MOVE... then an ACTION_CANCEL... and then the further ACTION_MOVE events start to get detected on the parent views.

In the SmoothScrollExitUntilCollapsedActivity case the ACTION_CANCEL is never received by the clickable view and the ACTION_MOVE events never get received by it's parents.

---

You both mentioned something about "dispatching the touch events on my own" but I need a bit more help about how to do that.... should I be detecting the ACTION_MOVE onTouch events (I already have this) and dispatching them (using the dispatchTouchEvent function ?) but... to who ? to the CoordinatorLayout ?
