### ISSUE TITLE
Changing tabs make the offset jump 

### ISSUE THREAD

**Issue by juliooa** [henrytao-me/smooth-app-bar-layout#77]
Hi Henry! me again, sorry I have another problem, I was trying to figure it out how to solved but I'm not making too much progress.

Is the same code from this fork:
https://github.com/juliooa/smooth-app-bar-layout/tree/feature/custom-view-header

Here is a video of the problem:
https://www.youtube.com/watch?v=w2UFKPpLAoE&feature=youtu.be

The problem just happened when the header is not totally collapsed or expanded. I was trying to force all the recycleviews to go back to the original position if any of the tabs starts to detach from the collapsed position, like the behavior when is fully expanded; but well, not luck until now.

Thanks again Henry.

**Comment by henrytao-me** [comment]
Hi @juliooa 

It's not an issue. It's a trade off. It's tricky to maintain the correct offset on each ViewPager Tab when switching between them. I would say it's not too bad for now. 

However, if you want to improve it, you totally can investigate but it has complex use cases. Check out here: 

`PagerWithHeaderFragment.java`

``` java
@Override
  public boolean onOffsetChanged(SmoothAppBarLayout smoothAppBarLayout, View target, int verticalOffset) {
    return Utils.syncOffset(smoothAppBarLayout, target, verticalOffset, getScrollTarget());
  }
```

Every time you call on current tab, `onOffsetChanged` will be called for current fragment and also propagate scroll event to all other tabs fragment if they are already initiated. `Utils.syncOffset` is default behavior. You can extend it to solve more complex use cases. 

My suggestions: 
- Ignore this issue and keep building your app. It's not too bad. 
- I will keep improving `Utils.syncOffset` so that it will be transparent to your code. 

I hope it helps.
Cheers, 
Henry

**Comment by juliooa** [comment]
Hi @henrytao-me, I understand, a trade off. I see the complexity about the use cases and also in your code to manage that complexity, thanks man, you can close this issue.
